config/routes.rb
Bookstore::Application.routes.draw do  
  resources :books do
    resources :reviews, except: [:index]
  end
end

app/models/book.rb
class Book < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  attr_accessible :name, :pages, :summary
  
  validates_presence_of :name
  validates_numericality_of :pages, greater_than: 0, allow_blank: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :book
  attr_accessible :body, :name, :rating
  
  validates_presence_of :name, :body, :rating
  validates_numericality_of :rating, only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  
  def show
    @book = Book.find params[:id]
    @reviews = @book.reviews
  end
  
  def new
    @book = Book.new
  end
  
  def create
    @book = Book.new params[:book]
    if @book.save
      redirect_to @book
    else
      render "new"
    end
  end
  
  def edit
    @book = Book.find params[:id]
  end
  
  def update
    @book = Book.find params[:id]
    if @book.update_attributes params[:book]
      redirect_to @book
    else
      render "edit"
    end
  end
  
  def destroy
    @book = Book.find params[:id]
    @book.destroy
    redirect_to books_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_filter :find_book 
  
  def show
    @review = @book.reviews.find params[:id]
  end
  
  def new
    @review = @book.reviews.new
  end
  
  def create
    @review = @book.reviews.new params[:review]
    if @review.save
      redirect_to [@book, @review]
    else
      render "new"
    end
  end
  
  def edit
    @review = @book.reviews.find params[:id]
  end
  
  def update
    @review = @book.reviews.find params[:id]
    if @review.update_attributes params[:review]
      redirect_to [@book, @review]
    else
      render "edit"
    end
  end
  
  def destroy
    @review = @book.reviews.find params[:id]
    @review.destroy
    redirect_to @book
  end
  
  private
  
  def find_book
    @book = Book.find params[:book_id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/books/_form.html.erb
<%= simple_form_for @book do |f| %>
  <%= f.input :name %>
  <%= f.input :pages %>
  <%= f.input :summary %>
  
<%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/books/edit.html.erb
<%= render partial: "form" %>

app/views/books/index.html.erb
<h1>Books</h1>

<%= link_to "New Book", new_book_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Pages</th>
    <th>Review Count</th>
  </tr>
  <% @books.each do |book| %>
  <tr>
    <td><%= link_to book.name, book %></td>
    <td><%= book.pages %></td>
    <td><%= book.reviews.count %></td>
  </tr>
  <% end %>
</table>

app/views/books/new.html.erb
<%= render partial: "form" %>

app/views/books/show.html.erb
<h1><%= @book.name %></h1>

<%= link_to "Edit", edit_book_path(@book) %> | 
<%= link_to "Delete", @book, method: :delete, data:{confirm: "Are you sure?"} %>
<p>Pages: <%= @book.pages %></p>
<p><%= simple_format @book.summary %></p>

<h2>Reviews</h2>

<%= link_to "Add Review", new_book_review_path(@book) %>

<% @reviews.each do |review| %>
<div>
  <%= simple_format review.body %>
  <%= link_to [@book, review] do %>
    <p style="font-style: italic"><%= review.name %> gave this book a <%= review.rating %> star rating.</p>
  <% end %>
</div>
<% end %>

<%= link_to "All Books", books_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookstore</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= simple_form_for [@book, @review] do |f| %>
  <%= f.input :name %>
  <%= f.input :rating, as: :select, collection: 1..5 %>
  <%= f.input :body %>

  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/reviews/edit.html.erb
<%= render "form" %>

app/views/reviews/new.html.erb
<%= form_for [@book, @review] do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :rating %>
    <%= f.text_field :rating %>
  </div>
  <div>
    <%= f.label :body %>
    <%= f.text_area :body %>
  </div>

  <%= f.submit %>
<% end %>

app/views/reviews/show.html.erb
<h1>Review #<%= @review.id %> for <%= link_to @book.name, @book %></h1>

<%= link_to "Edit", edit_book_review_path(@book, @review) %> | 
<%= link_to "Delete", [@book, @review], method: :delete, data: {confirm: "Are you sure?"} %>

<p><%= @review.name %> gave this book <%= @review.rating %> stars</p>

<%= simple_format @review.body %>